SELECT * FROM escola AS e1

LEFT JOIN turma AS e2 
ON e1.CO_ENTIDADE = e2.CO_ENTIDADE

LEFT JOIN gestor_escolar AS e3
ON e1.CO_ENTIDADE = e3.CO_ENTIDADE

LEFT JOIN matricula AS e4
ON e1.CO_ENTIDADE = e4.CO_ENTIDADE

LEFT JOIN docente AS e5
ON e1.CO_ENTIDADE = e5.CO_ENTIDADE

WHERE e1.NO_MUNICIPIO = 'Santa Maria' 
      AND e1.SG_UF = 'RS'
