SELECT
    CO_ESCOLA,
    COUNT(*)                       AS QT_ALUNOS,
    ROUND(AVG(NU_NOTA_CN), 1)      AS MEDIA_CN,
    ROUND(AVG(NU_NOTA_CH), 1)      AS MEDIA_CH,
    ROUND(AVG(NU_NOTA_LC), 1)      AS MEDIA_LC,
    ROUND(AVG(NU_NOTA_MT), 1)      AS MEDIA_MT,
    ROUND(AVG(NU_NOTA_REDACAO), 1) AS MEDIA_RED,
    ROUND(
        (AVG(NU_NOTA_CN) + AVG(NU_NOTA_CH) + AVG(NU_NOTA_LC) + AVG(NU_NOTA_MT) + AVG(NU_NOTA_REDACAO)) / 5.0
    , 1)                           AS MEDIA_GERAL
FROM resultados
WHERE SG_UF_ESC = 'RS'
GROUP BY CO_ESCOLA
ORDER BY MEDIA_GERAL DESC;
